gains:

  head_1_joint:                   {p: 300,  d: 0.1, i: 1, i_clamp: 5, torque_clamp: 8}
  head_2_joint:                   {p: 300,  d: 0.1, i: 1, i_clamp: 1.5, torque_clamp: 8}

  torso_1_joint:                  {p: 10000, d: 10, i: 1, i_clamp: 10, torque_clamp: 100}
  torso_2_joint:                  {p: 10000, d: 10, i: 1, i_clamp: 10, torque_clamp: 100}

  arm_right_1_joint: &arm_1_gains {p: 10000, d: 0, i: 0,  i_clamp: 14, torque_clamp: 150}
  arm_right_2_joint: &arm_2_gains {p: 10000, d: 0, i: 0,  i_clamp: 14, torque_clamp: 150}
  arm_right_3_joint: &arm_3_gains {p: 5000, d: 0, i: 0,  i_clamp: 9, torque_clamp: 100}
  arm_right_4_joint: &arm_4_gains {p: 10000, d: 0, i: 0,  i_clamp: 9, torque_clamp: 100}
  arm_right_5_joint: &arm_5_gains {p: 3000,  d: 0, i: 0, i_clamp: 5, torque_clamp: 50}
  arm_right_6_joint: &arm_6_gains {p: 3000,  d: 0, i: 0, i_clamp: 3, torque_clamp: 30}
  arm_right_7_joint: &arm_7_gains {p: 3000,  d: 0, i: 0, i_clamp: 3, torque_clamp: 30}
  arm_left_1_joint:  *arm_1_gains
  arm_left_2_joint:  *arm_2_gains
  arm_left_3_joint:  *arm_3_gains
  arm_left_4_joint:  *arm_4_gains
  arm_left_5_joint:  *arm_5_gains
  arm_left_6_joint:  *arm_6_gains
  arm_left_7_joint:  *arm_7_gains

  hand_right_index_abd_joint: &finger_gains {p: 50, d: 0.1, i: 0.1, i_clamp: 1}
  hand_right_index_virtual_1_joint: *finger_gains
  hand_right_index_virtual_2_joint: *finger_gains
  hand_right_index_virtual_3_joint: *finger_gains
  hand_right_index_flex_1_joint: *finger_gains
  hand_right_index_flex_2_joint: *finger_gains
  hand_right_index_flex_3_joint: *finger_gains
  hand_right_index_joint: *finger_gains
  hand_right_little_abd_joint: *finger_gains
  hand_right_little_virtual_1_joint: *finger_gains
  hand_right_little_virtual_2_joint: *finger_gains
  hand_right_little_virtual_3_joint: *finger_gains
  hand_right_little_flex_1_joint: *finger_gains
  hand_right_little_flex_2_joint: *finger_gains
  hand_right_little_flex_3_joint: *finger_gains
  hand_right_middle_abd_joint: *finger_gains
  hand_right_middle_virtual_1_joint: *finger_gains
  hand_right_middle_virtual_2_joint: *finger_gains
  hand_right_middle_virtual_3_joint: *finger_gains
  hand_right_middle_flex_1_joint: *finger_gains
  hand_right_middle_flex_2_joint: *finger_gains
  hand_right_middle_flex_3_joint: *finger_gains
  hand_right_ring_abd_joint: *finger_gains
  hand_right_ring_virtual_1_joint: *finger_gains
  hand_right_ring_virtual_2_joint: *finger_gains
  hand_right_ring_virtual_3_joint: *finger_gains
  hand_right_ring_flex_1_joint: *finger_gains
  hand_right_ring_flex_2_joint: *finger_gains
  hand_right_ring_flex_3_joint: *finger_gains
  hand_right_thumb_abd_joint: *finger_gains
  hand_right_thumb_virtual_1_joint: *finger_gains
  hand_right_thumb_virtual_2_joint: *finger_gains
  hand_right_thumb_virtual_3_joint: *finger_gains
  hand_right_thumb_flex_1_joint: *finger_gains
  hand_right_thumb_flex_2_joint: *finger_gains
  hand_right_thumb_flex_3_joint: *finger_gains
  hand_right_thumb_joint: *finger_gains
  hand_right_mrl_joint: *finger_gains

  hand_left_index_abd_joint: *finger_gains
  hand_left_index_virtual_1_joint: *finger_gains
  hand_left_index_virtual_2_joint: *finger_gains
  hand_left_index_virtual_3_joint: *finger_gains
  hand_left_index_flex_1_joint: *finger_gains
  hand_left_index_flex_2_joint: *finger_gains
  hand_left_index_flex_3_joint: *finger_gains
  hand_left_index_joint: *finger_gains
  hand_left_little_abd_joint: *finger_gains
  hand_left_little_virtual_1_joint: *finger_gains
  hand_left_little_virtual_2_joint: *finger_gains
  hand_left_little_virtual_3_joint: *finger_gains
  hand_left_little_flex_1_joint: *finger_gains
  hand_left_little_flex_2_joint: *finger_gains
  hand_left_little_flex_3_joint: *finger_gains
  hand_left_middle_abd_joint: *finger_gains
  hand_left_middle_virtual_1_joint: *finger_gains
  hand_left_middle_virtual_2_joint: *finger_gains
  hand_left_middle_virtual_3_joint: *finger_gains
  hand_left_middle_flex_1_joint: *finger_gains
  hand_left_middle_flex_2_joint: *finger_gains
  hand_left_middle_flex_3_joint: *finger_gains
  hand_left_ring_abd_joint: *finger_gains
  hand_left_ring_virtual_1_joint: *finger_gains
  hand_left_ring_virtual_2_joint: *finger_gains
  hand_left_ring_virtual_3_joint: *finger_gains
  hand_left_ring_flex_1_joint: *finger_gains
  hand_left_ring_flex_2_joint: *finger_gains
  hand_left_ring_flex_3_joint: *finger_gains
  hand_left_thumb_abd_joint: *finger_gains
  hand_left_thumb_virtual_1_joint: *finger_gains
  hand_left_thumb_virtual_2_joint: *finger_gains
  hand_left_thumb_virtual_3_joint: *finger_gains
  hand_left_thumb_flex_1_joint: *finger_gains
  hand_left_thumb_flex_2_joint: *finger_gains
  hand_left_thumb_flex_3_joint: *finger_gains
  hand_left_thumb_joint: *finger_gains
  hand_left_mrl_joint: *finger_gains