left_arm_dynamic_controller:
  type: "effort_controllers/DirectDynamicController"
  check_mode: True
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  actuators:
    - arm_left_1_motor
    - arm_left_2_motor
    - arm_left_3_motor
    - arm_left_4_motor
    - arm_left_5_motor
    - arm_left_6_motor
    - arm_left_7_motor

  links:
    - torso_2_link
    - arm_left_7_link

  Kp:
    - 500
    - 800
    - 1000
    - 2000
    - 6000
    - 70000
    - 150000
  Kv:
    - 50
    - 80
    - 100
    - 100
    - 500
    - 7000
    - 15000
  
  controller_type: "Computed_torque"

  lambda: 0.5
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    arm_left_1_joint:
      goal: &goal_pos_constraint 0.05
    arm_left_2_joint:
      goal: *goal_pos_constraint
    arm_left_3_joint:
      goal: *goal_pos_constraint
    arm_left_4_joint:
      goal: *goal_pos_constraint
    arm_left_5_joint:
      goal: *goal_pos_constraint
    arm_left_6_joint:
      goal: *goal_pos_constraint
    arm_left_7_joint:
      goal: *goal_pos_constraint


  stop_trajectory_duration: 0.0

