motor_params:
    arm_left_1_joint:
      type: actuated
      motor_torque_constant: 0.136
      reduction_ratio: 100.0
    arm_left_2_joint:
      type: actuated
      motor_torque_constant: 0.136
      reduction_ratio: 100.0
    arm_left_3_joint:
      type: actuated
      motor_torque_constant: -0.087
      reduction_ratio: 100.0
    arm_left_4_joint:
      type: actuated
      motor_torque_constant: -0.087
      reduction_ratio: 100
    arm_left_5_joint:
      type: actuated
      motor_torque_constant: 0.0
      reduction_ratio: 0.0
    arm_left_6_joint:
      type: actuated
      motor_torque_constant: 0.0
      reduction_ratio: 0.0
    arm_left_7_joint:
      type: actuated
      motor_torque_constant: 0.0
      reduction_ratio: 0.0
