head_controller:
  type: "position_controllers/JointTrajectoryController"
  check_mode: True
  joints:
    - head_1_joint
    - head_2_joint
  actuators:
    - head_1_motor
    - head_2_motor

  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    head_1_joint:
      goal: &goal_pos_constraint 0.02
    head_2_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0


  pan_link:  head_1_link
  tilt_link: head_2_link
  success_angle_threshold: 0.01
