left_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  check_mode: True
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
  actuators:
    - leg_left_1_motor
    - leg_left_2_motor
    - leg_left_3_motor
    - leg_left_4_motor
    - leg_left_5_motor
    - leg_left_6_motor
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    arm_left_1_joint:
      goal: &goal_pos_constraint 0.02
    arm_left_2_joint:
      goal: *goal_pos_constraint
    arm_left_3_joint:
      goal: *goal_pos_constraint
    arm_left_4_joint:
      goal: *goal_pos_constraint
    arm_left_5_joint:
      goal: *goal_pos_constraint
    arm_left_6_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0
