torso_controller:
  type: "position_controllers/JointTrajectoryController"
  check_mode: True
  joints:
    - torso_1_joint
    - torso_2_joint
  actuators:
    - torso_1_motor
    - torso_2_motor

  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    torso_1_joint:
      goal: &goal_pos_constraint 0.02
    torso_2_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0
