# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from astronaut_controllers/plot_jnt.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class plot_jnt(genpy.Message):
  _md5sum = "3b09b9904d6a381558d8c771bafb8d82"
  _type = "astronaut_controllers/plot_jnt"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 jnt_0
float64 jnt_1
float64 jnt_2
float64 jnt_3
float64 jnt_4
float64 jnt_5
float64 jnt_6




"""
  __slots__ = ['jnt_0','jnt_1','jnt_2','jnt_3','jnt_4','jnt_5','jnt_6']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       jnt_0,jnt_1,jnt_2,jnt_3,jnt_4,jnt_5,jnt_6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(plot_jnt, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.jnt_0 is None:
        self.jnt_0 = 0.
      if self.jnt_1 is None:
        self.jnt_1 = 0.
      if self.jnt_2 is None:
        self.jnt_2 = 0.
      if self.jnt_3 is None:
        self.jnt_3 = 0.
      if self.jnt_4 is None:
        self.jnt_4 = 0.
      if self.jnt_5 is None:
        self.jnt_5 = 0.
      if self.jnt_6 is None:
        self.jnt_6 = 0.
    else:
      self.jnt_0 = 0.
      self.jnt_1 = 0.
      self.jnt_2 = 0.
      self.jnt_3 = 0.
      self.jnt_4 = 0.
      self.jnt_5 = 0.
      self.jnt_6 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.jnt_0, _x.jnt_1, _x.jnt_2, _x.jnt_3, _x.jnt_4, _x.jnt_5, _x.jnt_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.jnt_0, _x.jnt_1, _x.jnt_2, _x.jnt_3, _x.jnt_4, _x.jnt_5, _x.jnt_6,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.jnt_0, _x.jnt_1, _x.jnt_2, _x.jnt_3, _x.jnt_4, _x.jnt_5, _x.jnt_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.jnt_0, _x.jnt_1, _x.jnt_2, _x.jnt_3, _x.jnt_4, _x.jnt_5, _x.jnt_6,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
