# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from astronaut_controllers/plot_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class plot_msg(genpy.Message):
  _md5sum = "2e3b1b0cf6c1e9ca2b791e3388980632"
  _type = "astronaut_controllers/plot_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x_err
float64 y_err
float64 z_err
float64 roll_err
float64 pitch_err
float64 yaw_err




"""
  __slots__ = ['x_err','y_err','z_err','roll_err','pitch_err','yaw_err']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_err,y_err,z_err,roll_err,pitch_err,yaw_err

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(plot_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x_err is None:
        self.x_err = 0.
      if self.y_err is None:
        self.y_err = 0.
      if self.z_err is None:
        self.z_err = 0.
      if self.roll_err is None:
        self.roll_err = 0.
      if self.pitch_err is None:
        self.pitch_err = 0.
      if self.yaw_err is None:
        self.yaw_err = 0.
    else:
      self.x_err = 0.
      self.y_err = 0.
      self.z_err = 0.
      self.roll_err = 0.
      self.pitch_err = 0.
      self.yaw_err = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.x_err, _x.y_err, _x.z_err, _x.roll_err, _x.pitch_err, _x.yaw_err))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_err, _x.y_err, _x.z_err, _x.roll_err, _x.pitch_err, _x.yaw_err,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.x_err, _x.y_err, _x.z_err, _x.roll_err, _x.pitch_err, _x.yaw_err))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_err, _x.y_err, _x.z_err, _x.roll_err, _x.pitch_err, _x.yaw_err,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
