# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_left_1_joint:
    has_velocity_limits: true
    max_velocity: 2.7
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_2_joint:
    has_velocity_limits: true
    max_velocity: 3.66
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_3_joint:
    has_velocity_limits: true
    max_velocity: 4.58
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_4_joint:
    has_velocity_limits: true
    max_velocity: 4.58
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_5_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_6_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  arm_left_7_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_1_joint:
    has_velocity_limits: true
    max_velocity: 2.7
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_2_joint:
    has_velocity_limits: true
    max_velocity: 3.66
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_3_joint:
    has_velocity_limits: true
    max_velocity: 4.58
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_4_joint:
    has_velocity_limits: true
    max_velocity: 4.58
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_5_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_6_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  arm_right_7_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_fingertip_1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_fingertip_2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_fingertip_3_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_inner_double_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_inner_single_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_motor_single_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_fingertip_1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_fingertip_2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_fingertip_3_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_inner_double_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_inner_single_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_motor_single_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  leg_left_1_joint:
    has_velocity_limits: true
    max_velocity: 3.87
    has_acceleration_limits: false
    max_acceleration: 0
  leg_left_2_joint:
    has_velocity_limits: true
    max_velocity: 5.8
    has_acceleration_limits: false
    max_acceleration: 0
  leg_left_3_joint:
    has_velocity_limits: true
    max_velocity: 5.8
    has_acceleration_limits: false
    max_acceleration: 0
  leg_left_4_joint:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  leg_left_5_joint:
    has_velocity_limits: true
    max_velocity: 5.8
    has_acceleration_limits: false
    max_acceleration: 0
  leg_left_6_joint:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  leg_right_1_joint:
    has_velocity_limits: true
    max_velocity: 3.87
    has_acceleration_limits: false
    max_acceleration: 0
  leg_right_2_joint:
    has_velocity_limits: true
    max_velocity: 5.8
    has_acceleration_limits: false
    max_acceleration: 0
  leg_right_3_joint:
    has_velocity_limits: true
    max_velocity: 5.8
    has_acceleration_limits: false
    max_acceleration: 0
  leg_right_4_joint:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  leg_right_5_joint:
    has_velocity_limits: true
    max_velocity: 5.8
    has_acceleration_limits: false
    max_acceleration: 0
  leg_right_6_joint:
    has_velocity_limits: true
    max_velocity: 4.8
    has_acceleration_limits: false
    max_acceleration: 0
  torso_1_joint:
    has_velocity_limits: true
    max_velocity: 5.4
    has_acceleration_limits: false
    max_acceleration: 0
  torso_2_joint:
    has_velocity_limits: true
    max_velocity: 5.4
    has_acceleration_limits: false
    max_acceleration: 0