astronaut_head_tilt_controller:
  type: effort_controllers/JointPositionController
  joint: head_1_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}

astronaut_head_pan_controller:
  type: effort_controllers/JointPositionController
  joint: head_2_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}

