my_cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "wrist_right_ft_tool_link"
    robot_base_link: "dummy_base_link"
    target_frame_topic: "target_frame"
    joints:
    - torso_1_joint
    - torso_2_joint
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint

    pd_gains:
        trans_x: {p: 10.0}
        trans_y: {p: 10.0}
        trans_z: {p: 10.0}
        rot_x: {p: 1.0}
        rot_y: {p: 1.0}
        rot_z: {p: 1.0}