# Position Controllers ---------------------------------------
joint_1_astro_right_arm:
  type: effort_controllers/JointPositionController
  joint: arm_right_1_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}
joint_2_astro_right_arm:
  type: effort_controllers/JointPositionController
  joint: arm_right_2_joint
  pid: {p: 2500.0, i: 10.0, d: 100.0}
joint_3_astro_right_arm:
  type: effort_controllers/JointPositionController
  joint: arm_right_3_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}
joint_4_astro_right_arm:
  type: effort_controllers/JointPositionController
  joint: arm_right_4_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}
joint_5_astro_right_arm:
  type: effort_controllers/JointPositionController
  joint: arm_right_5_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}
joint_6_astro_right_arm:
  type: effort_controllers/JointPositionController
  joint: arm_right_6_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}
joint_7_astro_right_arm:
  type: effort_controllers/JointPositionController
  joint: arm_right_7_joint
  pid: {p: 500.0, i: 10.0, d: 1.0}

  
