teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.15
      -
        axis: 0
        target: angular.z
        scale: 0.25
      -
        axis: 2
        target: linear.y
        scale: 0.15

  joy_priority:
    type: action
    action_name: joy_priority_action
    buttons: [0]

  # undocumented poses, with 'back' button
  home:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: home
    buttons: [8, 1]

  hands_walk:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: walk_pose
    buttons: [8, 2]

  # documented motions, with right upper button and right trigger
  # see SDE4 documentation
  wave:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: wave
    buttons: [5, 1]

  bow:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: bow
    buttons: [5, 0]

  open_arms:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: wave_both_arms
    buttons: [5, 3]

  shake_hand:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: lift_weights
    buttons: [5, 2]

