actuators:
  raw_data:
    position_port: act_position
    velocity_port: act_velocity
    effort_port: act_current
    mode_port: act_control_mode
    position_cmd_port: ref_position
    effort_cmd_port: ref_current
    mode_cmd_port: ref_control_mode
    absolute_encoder_position_port: act_abs_position
    torque_sensor_port: act_torque
    temperature_sensor_port: act_temperature
    current_limit_cmd_port: ref_limit_current

e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

#ros_control_component:
#  ignore_read_errors: true
