ConfigurationInitializerParameters:
  control_interval: 0.001
  max_joint_velocity_factor: 0.05
  initialize_fixed_joints: true
  joint_states_topic: /joint_states
  goal_tolerance:
    position: 0.1
    velocity: 0.2
    acceleration: 2
    name: ""
    time_sec: 10
  dispatcher_parameters:
    dispatcher_waiting_time_sec: 5.0
    ignore_controller_failure: false
    wait_joint_not_found: 5.0

URDFModelParameters:
  default_configuration_paramserver_prefix: "/zeros"
  robot_description_parameter: "robot_description"
  robot_description_parameter_override: "urdf_xml_model"
  exclusive_tips: []
  omit_links: []
  fix_joints: []
  fix_links_recursive: []
  kinematic_root_override: ""
  kinematic_root_override_transform:
    cols: 4
    rows: 4
    data: [1, 0, 0, 0,
           0, 1, 0, 0,
           0, 0, 1, 0,
           0, 0, 0, 0]
  joint_limit_safety_margin: 0.05
  joints_reflection: []

PlanningModelParameters:
  planning_time_limit: 10.0
  simplification_time_limit: 0.0
  validity_checking_resolution: 0.005
  dist_invalid_start: 0.0
  check_self_collisions: true
