init_offset_controller:
  type: reemc_controllers/ReemcInitOffsetController 
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
  left_ft_sensor: left_ankle_ft
  right_ft_sensor: right_ankle_ft
  base_imu_sensor: base_imu

  hip_spacing_x: -0.04
  hip_spacing_y: 0.085
  hip_spacing_z: 0.0

  femur_length: 0.380
  tibia_length: 0.320
  foot_height: 0.107
  ft_sensor_z: 0.02

  config_folder: "$HOME/.pal/init_offset_controller/config"
