loop_counter_factor: -1
debug_backdoor: true

odometry:
   enabled        : true
   vel_window_size: 10
   use_imu_yaw    : false
   publish_rate   : 100.0

   pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 0.1, 0.1, 0.1]
   twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 0.1, 0.1, 0.1]

biped_controller:
   delta_T: 0.0005
   ft_sensor_z: 0.02
   variable_joint_offset_hip: -0.7
   variable_joint_offset_ankle: -0.7
   swing_foot_z: 0.03
   z_lipm: 1.05

com_stabilizer:
   ds_x_p: 0.5
   ds_y_p: 0.5
   ss_x_p: 0.5
   ss_y_p: 0.5
   dead_zone: 0.005
   foot_offset_clamp: 0.03
   hip_offset_x_clamp: 0.04
   hip_offset_y_clamp: 0.04
   hip_offset_decay: 0.997
   ss_min_weight: 150

hip_spacing_x: -0.04
hip_spacing_y: 0.085
hip_spacing_z: 0.0
femur_length: 0.380
tibia_length: 0.320
foot_height: 0.107
hip_down_default: 0.04

read_absolute_encoders: False
