motor_params:
    leg_right_1_joint:
      type: actuated
      motor_torque_constant: 0.136
      reduction_ratio: 100.0
    leg_right_2_joint:
      type: actuated
      motor_torque_constant: 0.136
      reduction_ratio: 100.0
    leg_right_3_joint:
      type: actuated
      motor_torque_constant: -0.087
      reduction_ratio: 100.0
    leg_right_4_joint:
      type: actuated
      motor_torque_constant: -0.087
      reduction_ratio: 100
    leg_right_5_joint:
      type: actuated
      motor_torque_constant: 0.0
      reduction_ratio: 0.0
    leg_right_6_joint:
      type: actuated
      motor_torque_constant: 0.0
      reduction_ratio: 0.0
