// Generated by gencpp from file astronaut_controllers/hand_operations.msg
// DO NOT EDIT!


#ifndef ASTRONAUT_CONTROLLERS_MESSAGE_HAND_OPERATIONS_H
#define ASTRONAUT_CONTROLLERS_MESSAGE_HAND_OPERATIONS_H

#include <ros/service_traits.h>


#include <astronaut_controllers/hand_operationsRequest.h>
#include <astronaut_controllers/hand_operationsResponse.h>


namespace astronaut_controllers
{

struct hand_operations
{

typedef hand_operationsRequest Request;
typedef hand_operationsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hand_operations
} // namespace astronaut_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astronaut_controllers::hand_operations > {
  static const char* value()
  {
    return "e64cddebc1c701e9b45008b7ec9f9d6d";
  }

  static const char* value(const ::astronaut_controllers::hand_operations&) { return value(); }
};

template<>
struct DataType< ::astronaut_controllers::hand_operations > {
  static const char* value()
  {
    return "astronaut_controllers/hand_operations";
  }

  static const char* value(const ::astronaut_controllers::hand_operations&) { return value(); }
};


// service_traits::MD5Sum< ::astronaut_controllers::hand_operationsRequest> should match 
// service_traits::MD5Sum< ::astronaut_controllers::hand_operations > 
template<>
struct MD5Sum< ::astronaut_controllers::hand_operationsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astronaut_controllers::hand_operations >::value();
  }
  static const char* value(const ::astronaut_controllers::hand_operationsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astronaut_controllers::hand_operationsRequest> should match 
// service_traits::DataType< ::astronaut_controllers::hand_operations > 
template<>
struct DataType< ::astronaut_controllers::hand_operationsRequest>
{
  static const char* value()
  {
    return DataType< ::astronaut_controllers::hand_operations >::value();
  }
  static const char* value(const ::astronaut_controllers::hand_operationsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astronaut_controllers::hand_operationsResponse> should match 
// service_traits::MD5Sum< ::astronaut_controllers::hand_operations > 
template<>
struct MD5Sum< ::astronaut_controllers::hand_operationsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astronaut_controllers::hand_operations >::value();
  }
  static const char* value(const ::astronaut_controllers::hand_operationsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astronaut_controllers::hand_operationsResponse> should match 
// service_traits::DataType< ::astronaut_controllers::hand_operations > 
template<>
struct DataType< ::astronaut_controllers::hand_operationsResponse>
{
  static const char* value()
  {
    return DataType< ::astronaut_controllers::hand_operations >::value();
  }
  static const char* value(const ::astronaut_controllers::hand_operationsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRONAUT_CONTROLLERS_MESSAGE_HAND_OPERATIONS_H
