// Generated by gencpp from file astronaut_controllers/hand_operationsRequest.msg
// DO NOT EDIT!


#ifndef ASTRONAUT_CONTROLLERS_MESSAGE_HAND_OPERATIONSREQUEST_H
#define ASTRONAUT_CONTROLLERS_MESSAGE_HAND_OPERATIONSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace astronaut_controllers
{
template <class ContainerAllocator>
struct hand_operationsRequest_
{
  typedef hand_operationsRequest_<ContainerAllocator> Type;

  hand_operationsRequest_()
    : operation()
    , hand()  {
    }
  hand_operationsRequest_(const ContainerAllocator& _alloc)
    : operation(_alloc)
    , hand(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _operation_type;
  _operation_type operation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hand_type;
  _hand_type hand;





  typedef boost::shared_ptr< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct hand_operationsRequest_

typedef ::astronaut_controllers::hand_operationsRequest_<std::allocator<void> > hand_operationsRequest;

typedef boost::shared_ptr< ::astronaut_controllers::hand_operationsRequest > hand_operationsRequestPtr;
typedef boost::shared_ptr< ::astronaut_controllers::hand_operationsRequest const> hand_operationsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace astronaut_controllers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dc96464fdf846c4cccabcfccb47a88f";
  }

  static const char* value(const ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dc96464fdf846c4ULL;
  static const uint64_t static_value2 = 0xcccabcfccb47a88fULL;
};

template<class ContainerAllocator>
struct DataType< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "astronaut_controllers/hand_operationsRequest";
  }

  static const char* value(const ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string operation\n\
string hand\n\
\n\
";
  }

  static const char* value(const ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.operation);
      stream.next(m.hand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hand_operationsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::astronaut_controllers::hand_operationsRequest_<ContainerAllocator>& v)
  {
    s << indent << "operation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.operation);
    s << indent << "hand: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASTRONAUT_CONTROLLERS_MESSAGE_HAND_OPERATIONSREQUEST_H
