## Follow the following format to set the robot specific parameters to each joint

# leg_right_5_joint:
#   dob_params:
#     bias_evolution_covariance: 0.01
#     oscilator_evolution_covariance: 0.01
#     measurement_covariance: 10.0
#     dob_bias_gain: 0.9