static_friction: 0.0
viscous_friction: 0.0
velocity_tolerance: 0.0

velocity_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      
      cutoff1: 50.0
      cutoff2: 0.0

command_filter:
  filter_parameters:
    - order: 5
      type: LowPass
      composition_type: Sequence
      
      cutoff1: 50.0
      cutoff2: 0.0
