force_torque:
  left_wrist_ft:
    frame: wrist_left_ft_link
    transformation:
      force: [x, y, -z]
      torque: [x, y, -z]
    raw_data:
      force_port: force_wrist_left
      torque_port: torque_wrist_left
