arm_left_1_joint:
  actuator_params:
    torque_sensor_offset: 4.0
arm_left_2_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_left_3_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_left_4_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_left_5_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_left_6_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_left_7_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_right_1_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_right_2_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_right_3_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_right_4_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_right_5_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_right_6_joint:
  actuator_params:
    torque_sensor_offset: 0.0
arm_right_7_joint:
  actuator_params:
    torque_sensor_offset: 0.0
leg_left_1_joint:
  actuator_params:
    torque_sensor_offset: 0.0
leg_left_2_joint:
  actuator_params:
    torque_sensor_offset: 12.0
leg_left_3_joint:
  actuator_params:
    torque_sensor_offset: -3.0
leg_left_4_joint:
  actuator_params:
    torque_sensor_offset: 0.0
leg_left_5_joint:
  actuator_params:
    torque_sensor_offset: 3.0
leg_left_6_joint:
  actuator_params:
    torque_sensor_offset: -2.3
leg_right_1_joint:
  actuator_params:
    torque_sensor_offset: -1.5
leg_right_2_joint:
  actuator_params:
    torque_sensor_offset: -6.5
leg_right_3_joint:
  actuator_params:
    torque_sensor_offset: -3.0
leg_right_4_joint:
  actuator_params:
    torque_sensor_offset: 3.5
leg_right_5_joint:
  actuator_params:
    torque_sensor_offset: 0.0
leg_right_6_joint:
  actuator_params:
    torque_sensor_offset: 2.5
head_1_joint:
  actuator_params:
    torque_sensor_offset: 0.0
head_2_joint:
  actuator_params:
    torque_sensor_offset: 0.0
torso_1_joint:
  actuator_params:
    torque_sensor_offset: 0.0
torso_2_joint:
  actuator_params:
    torque_sensor_offset: 0.0
gripper_left_joint:
  actuator_params:
    torque_sensor_offset: 0.0
gripper_right_joint:
  actuator_params:
    torque_sensor_offset: 0.0
