motor_inertia: 0.000207288
motor_torque_constant: 0.1031
torque_sensor_offset: 12.0
reduction_ratio: 101
actuator_names:
  - leg_left_2_motor
check_mode: false
static_friction: 0.1
viscous_friction: 0.4
joint_elasticity: 10000.0
joint_elasticity_damping: -20.
