left_leg_dynamic_controller:
  type: "effort_controllers/DirectDynamicController"
  check_mode: True
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
  actuators:
    - leg_left_1_motor
    - leg_left_2_motor
    - leg_left_3_motor
    - leg_left_4_motor
    - leg_left_5_motor
    - leg_left_6_motor

  links:
    - base_link
    - leg_left_7_link

  Kp:
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
    - 1000
  Kv:
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100

  controller_type: "PD+"
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    leg_left_1_joint:
      goal: &goal_pos_constraint 0.02
    leg_left_2_joint:
      goal: *goal_pos_constraint
    leg_left_3_joint:
      goal: *goal_pos_constraint
    leg_left_4_joint:
      goal: *goal_pos_constraint
    leg_left_5_joint:
      goal: *goal_pos_constraint
    leg_left_6_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

